In [1]:
import numpy as np
import pandas as pd

In [2]:
train=pd.read_csv('Train.csv')     #here we are having separate dataset for train and test
test=pd.read_csv('Test.csv')

C:\Users\binod\AppData\Local\Temp\ipykernel_11260\1704959212.py:1: DtypeWarning: Columns (746,835) have mixed types. Specify dtype option on import or set low_memory=False.
  train=pd.read_csv('Train.csv')     #here we are having separate dataset for train and test
C:\Users\binod\AppData\Local\Temp\ipykernel_11260\1704959212.py:2: DtypeWarning: Columns (700,731,740,752,761,789,811,820,829,841,850) have mixed types. Specify dtype option on import or set low_memory=False.
  test=pd.read_csv('Test.csv')


In [3]:
train.head()           #Col1 contains unique id and Col2 is our target variable 

Col1  Col2          Col3          Col4          Col5          Col6  \
0    RIGHGSN     1  1.086711e+04  8.648345e+03  1.576618e+04  2.890466e+04   
1  RIMHI5ZGP     0  2.584312e+05  2.179633e+05  1.866287e+05  1.866287e+05   
2  RIHOG1SZU     0  1.459355e+07  1.260060e+07  1.100315e+07  1.010315e+07   
3  RIHOLMQWU     0  6.727043e+05  8.181116e+05  6.794893e+05  6.794893e+05   
4  RIHO584ET     0 -1.218742e+06 -3.005361e+06 -1.666241e+05 -2.403574e+06   

           Col7          Col8          Col9         Col10  ...  Col2388  \
0  5.273655e+03  2.346153e+04  1.285597e+04  2.871509e+04  ...        0   
1  2.154519e+05  1.923615e+05  1.726538e+05  1.666974e+05  ...        0   
2  1.879882e+07  1.514035e+07  5.320778e+06  6.906324e+06  ...        0   
3  8.257254e+05  7.605803e+05  3.577134e+05  4.236612e+05  ...        0   
4  2.583183e+06  2.086546e+06  5.938358e+06  5.446532e+06  ...        0   

   Col2389  Col2390  Col2391  Col2392  Col2393  Col2394  Col2395  Col2396  \
0        1        0        1    214.0    214.0     68.0     22.0     22.0   
1        0        0        0     41.0     41.0     38.0     12.0     12.0   
2        1        1        0    378.0    378.0    310.0     21.0     21.0   
3        0        0        0    702.0    702.0    644.0    951.0    951.0   
4        0        0        0   1305.0   1305.0   1211.0   2205.0   2205.0   

   Col2397  
0      7.0  
1     11.0  
2     16.0  
3    743.0  
4   1831.0  

[5 rows x 2395 columns]

In [4]:
test.head()       #so here Col2 is missing and our aim is to pridict the elements of Col2. Col1 contains unique id 

Col1          Col3          Col4          Col5          Col6  \
0  RIGD58ZWD  8.167140e+04  8.614542e+04  7.532296e+04  7.532296e+04   
1  RIH660YDS -1.362824e+07 -4.493043e+06 -3.777257e+06 -4.493043e+06   
2  RIH660Q96  1.302700e+06  1.341449e+06  1.240085e+06  1.341449e+06   
3  RIYDO15W1  1.932258e+05  1.454433e+05  1.929148e+05  1.454433e+05   
4  RIYBGC1ZD  3.913385e+05  1.987337e+05  1.703432e+05  1.987337e+05   

           Col7          Col8          Col9         Col10         Col11  ...  \
0  1.125174e+05  1.002778e+05  2.038915e+04  3.053853e+04  8.395911e+04  ...   
1 -4.749764e+06 -4.749764e+06  1.147556e+07  1.147556e+07  1.272055e+07  ...   
2  1.477503e+06  1.477503e+06  3.904086e+05  3.904086e+05  4.979106e+05  ...   
3  1.318250e+04  1.318250e+04  8.650108e+04  8.650108e+04  5.896693e+03  ...   
4  3.046536e+05  3.046536e+05  2.528307e+05  2.528307e+05  3.034449e+05  ...   

   Col2388  Col2389  Col2390  Col2391  Col2392  Col2393  Col2394  Col2395  \
0        0        0        0        0     44.0     44.0     23.0     41.0   
1        1        1        2        2   1234.0   1234.0    680.0    154.0   
2        0        0        0        0     33.0     24.0     19.0      3.0   
3        0        0        0        0      8.0      8.0      3.0      7.0   
4        0        0        0        0      7.0      7.0      7.0      6.0   

   Col2396  Col2397  
0     41.0     36.0  
1    153.0     86.0  
2      1.0      1.0  
3      7.0      3.0  
4      6.0      5.0  

[5 rows x 2394 columns]

In [5]:
print(train.shape)
print(test.shape)  #the difference in number of columns is due to the col2

(17521, 2395)
(20442, 2394)


In [6]:
train.info()    

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17521 entries, 0 to 17520
Columns: 2395 entries, Col1 to Col2397
dtypes: float64(844), int64(1548), object(3)
memory usage: 320.2+ MB


In [7]:
test.info()   #the number of columns containing object values are 3 and 12 respectively i think they should be equal 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20442 entries, 0 to 20441
Columns: 2394 entries, Col1 to Col2397
dtypes: float64(837), int64(1545), object(12)
memory usage: 373.4+ MB


In [8]:
train.isna().sum()

Col1          0
Col2          0
Col3          0
Col4          0
Col5          0
           ... 
Col2393    1174
Col2394    1186
Col2395    1174
Col2396    1174
Col2397    1186
Length: 2395, dtype: int64

In [9]:
test.isna().sum()

Col1          0
Col3          0
Col4          0
Col5          0
Col6          0
           ... 
Col2393    1259
Col2394    1278
Col2395    1259
Col2396    1259
Col2397    1278
Length: 2394, dtype: int64

In [10]:
train.select_dtypes(include = 'object')       #lets check the object columns of train dataset

Col1 Col747 Col836
0        RIGHGSN    NaN    NaN
1      RIMHI5ZGP    NaN    NaN
2      RIHOG1SZU    NaN    NaN
3      RIHOLMQWU    NaN    NaN
4      RIHO584ET    NaN    NaN
...          ...    ...    ...
17516    M9ERLMQ    NaN    NaN
17517    M1W6L8S    NaN    NaN
17518    MD5BL5K    NaN    NaN
17519    MYLOQ8Y    NaN    NaN
17520    M2YK6ON    NaN    NaN

[17521 rows x 3 columns]

In [11]:
test.select_dtypes(include='object')  #object columns of test dataset

Col1 Col702 Col733 Col742 Col754 Col763 Col791 Col813 Col822  \
0      RIGD58ZWD    NaN    NaN      0    NaN      0    NaN    NaN    NaN   
1      RIH660YDS    NaN    NaN      0    NaN      0    NaN    NaN    NaN   
2      RIH660Q96    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
3      RIYDO15W1    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
4      RIYBGC1ZD    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...          ...    ...    ...    ...    ...    ...    ...    ...    ...   
20437   OL0I6O5R    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
20438   OL0I65ZW    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
20439   OL0I6CXW    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
20440     O2VIUO    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
20441   M7VKV5QD    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

      Col831 Col843 Col852  
0          0    NaN      0  
1          0    NaN      0  
2        NaN    NaN    NaN  
3        NaN    NaN    NaN  
4        NaN    NaN    NaN  
...      ...    ...    ...  
20437    NaN    NaN    NaN  
20438    NaN    NaN    NaN  
20439    NaN    NaN    NaN  
20440    NaN    NaN    NaN  
20441    NaN    NaN    NaN  

[20442 rows x 12 columns]

In [12]:
train.describe()

Col2          Col3          Col4          Col5          Col6  \
count  17521.000000  1.752100e+04  1.752100e+04  1.752100e+04  1.752100e+04   
mean       0.100508  3.158967e+04  2.046540e+04  2.502937e+04  2.789385e+04   
std        0.300685  7.612897e+05  7.136908e+05  6.018207e+05  6.091245e+05   
min        0.000000 -8.555719e+07 -8.555719e+07 -7.011955e+07 -7.100920e+07   
25%        0.000000  2.742337e+03  2.007863e+03  1.857013e+03  2.562647e+03   
50%        0.000000  9.308060e+03  6.642857e+03  6.236503e+03  8.464355e+03   
75%        0.000000  3.053873e+04  2.156093e+04  2.068154e+04  2.773849e+04   
max        1.000000  1.459355e+07  1.288980e+07  1.478068e+07  1.178075e+07   

               Col7          Col8          Col9         Col10         Col11  \
count  1.752100e+04  1.752100e+04  1.752100e+04  1.752100e+04  1.752100e+04   
mean   2.597734e+04  3.302600e+04  2.912693e+04  2.971069e+04  3.617392e+04   
std    7.211998e+05  7.488433e+05  2.175595e+05  2.981508e+05  2.612427e+05   
min   -8.480658e+07 -9.016250e+07  0.000000e+00  0.000000e+00  0.000000e+00   
25%    2.973188e+03  3.822170e+03  1.824148e+03  1.787456e+03  3.505288e+03   
50%    1.036962e+04  1.303534e+04  5.705458e+03  5.536147e+03  8.832639e+03   
75%    2.645998e+04  3.359204e+04  1.852222e+04  1.753976e+04  2.341911e+04   
max    1.879882e+07  1.514035e+07  1.125630e+07  2.788633e+07  1.314762e+07   

       ...       Col2388       Col2389       Col2390       Col2391  \
count  ...  17521.000000  17521.000000  17521.000000  17521.000000   
mean   ...      0.736202      0.595343      0.773757      0.639005   
std    ...      0.910828      0.784953      0.921805      0.806286   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...      1.000000      1.000000      1.000000      1.000000   
max    ...      4.000000      4.000000      4.000000      4.000000   

            Col2392       Col2393       Col2394      Col2395       Col2396  \
count  16347.000000  16347.000000  16335.000000  16347.00000  16347.000000   
mean      55.540038     55.015416     35.180961     17.99584     17.539977   
std       53.269618     52.697069     34.956016     24.83891     24.685954   
min        0.000000      0.000000      0.000000      0.00000      0.000000   
25%       21.000000     21.000000     12.000000      9.00000      9.000000   
50%       42.000000     42.000000     27.000000     13.00000     13.000000   
75%       74.000000     73.000000     47.000000     21.00000     21.000000   
max     1305.000000   1305.000000   1211.000000   2205.00000   2205.000000   

            Col2397  
count  16335.000000  
mean      10.359657  
std       18.476447  
min        0.000000  
25%        5.000000  
50%        7.000000  
75%       12.000000  
max     1831.000000  

[8 rows x 2392 columns]

In [13]:
test.describe()

Col3          Col4          Col5          Col6          Col7  \
count  2.044200e+04  2.044200e+04  2.044200e+04  2.044200e+04  2.044200e+04   
mean   3.749822e+04  2.360107e+04  3.099296e+04  3.153122e+04  2.728287e+04   
std    8.090349e+05  6.659282e+05  6.434903e+05  6.422364e+05  6.588844e+05   
min   -6.766640e+07 -6.416449e+07 -2.951962e+07 -5.160258e+07 -6.282747e+07   
25%    3.037609e+03  2.255115e+03  2.081114e+03  2.788630e+03  3.028607e+03   
50%    1.076447e+04  7.793441e+03  7.511782e+03  1.022429e+04  1.075722e+04   
75%    3.444611e+04  2.380610e+04  2.329657e+04  3.127464e+04  2.776564e+04   
max    3.861868e+07  3.024852e+07  6.325956e+07  2.766654e+07  2.193012e+07   

               Col8          Col9         Col10         Col11         Col12  \
count  2.044200e+04  2.044200e+04  2.044200e+04  2.044200e+04  2.044200e+04   
mean   3.625497e+04  3.282116e+04  3.295643e+04  3.903867e+04  3.901378e+04   
std    6.710696e+05  3.642904e+05  3.831866e+05  4.169885e+05  4.400329e+05   
min   -5.448213e+07  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    3.903768e+03  1.966539e+03  1.908582e+03  3.270135e+03  2.960897e+03   
50%    1.369641e+04  6.529336e+03  6.173574e+03  8.926603e+03  8.363056e+03   
75%    3.611465e+04  2.015090e+04  1.929168e+04  2.482480e+04  2.306036e+04   
max    2.229041e+07  3.463760e+07  3.277868e+07  4.255362e+07  3.969719e+07   

       ...       Col2388       Col2389       Col2390       Col2391  \
count  ...  20442.000000  20442.000000  20442.000000  20442.000000   
mean   ...      0.634674      0.558262      0.670238      0.589864   
std    ...      0.853880      0.784091      0.867530      0.796850   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...      1.000000      1.000000      1.000000      1.000000   
max    ...      4.000000      4.000000      4.000000      4.000000   

            Col2392       Col2393       Col2394       Col2395       Col2396  \
count  19183.000000  19183.000000  19164.000000  19183.000000  19183.000000   
mean      49.688474     49.131366     31.288614     17.008341     16.527238   
std       62.765442     61.032971     38.698616     29.464562     29.155274   
min        0.000000      0.000000      0.000000      1.000000      1.000000   
25%       16.000000     16.000000     10.000000      8.000000      8.000000   
50%       35.000000     35.000000     22.000000     12.000000     12.000000   
75%       65.000000     64.000000     42.000000     20.000000     19.000000   
max     3598.000000   3597.000000   1946.000000   3104.000000   3104.000000   

            Col2397  
count  19164.000000  
mean       9.726936  
std       17.616897  
min        0.000000  
25%        4.000000  
50%        7.000000  
75%       12.000000  
max     1745.000000  

[8 rows x 2382 columns]

In [14]:
for columns in train.select_dtypes('object').columns:
    print(columns)
    print(train[columns].unique())

Col1
['RIGHGSN' 'RIMHI5ZGP' 'RIHOG1SZU' ... 'MD5BL5K' 'MYLOQ8Y' 'M2YK6ON']
Col747
[nan '-' '0' '1' 0.0 5.0 '3']
Col836
[nan '-' '0' 0.0 '5']


In [15]:
for tcolumns in test.select_dtypes('object').columns:
    print(tcolumns)
    print(test[tcolumns].unique())              #we will separate the unique id col1 and treat the other columns

Col1
['RIGD58ZWD' 'RIH660YDS' 'RIH660Q96' ... 'OL0I6CXW' 'O2VIUO' 'M7VKV5QD']
Col702
[nan 0.0 '0' '-']
Col733
[nan 0.349927106 0.23489684 0.2387925689999999 0.326225572
 -0.2099562639999999 0.0699854209999999 0.283473355 0.100574803
 -0.094491118 0.43723953 0.0 0.482371579 -0.223606798 -0.2309364019999999
 -0.287181807 0.365962527 0.188982237 -0.005459133 0.350883835
 -0.1223531269999999 0.203411286 -0.124833495 -1.11e-17 0.069161739
 0.2099562639999999 0.223606798 0.4902332889999999 0.3684670879999999 0.6
 -0.2 0.111762013 0.461541869 -5.55e-18 0.267600457 0.356890822 -0.6
 -3.97e-18 -0.120203624 0.2 0.447213596 0.338943084 -0.164954156
 0.399347441 0.039904182 -0.42405191 0.356429936 0.094491118 0.428811668
 -0.0699854209999999 0.456012469 -0.063718173 -0.188982237 -0.129791319
 -0.147929864 0.13703048 -0.216598788 0.3851774129999999 0.385473461
 0.401123362 0.4426266679999999 0.013413513 -0.582413089 0.154402328
 0.206839799 -0.221745896 -0.600004941 -0.565007326 -0.0003611359999999

In [16]:
X = train.drop(['Col1','Col2'], axis=1)        #lets separate the target variable and remove the unique id that is col1
y = train.Col2

XTest = test.drop(['Col1'], axis=1)    #all columns except Col1 goes in XTest

# data mining


In [17]:
def data_treatment(row):    #lets convert the sring and '-' to float and nan respectively
    if row == '-':            #first lets create a user defined function that will convert '-'to np.nan and string to float
        return np.nan
    else:
        return float(row)

In [18]:
treat_columns = list(X.select_dtypes('object').columns) + list(XTest.select_dtypes('object').columns)
print(len(treat_columns))
print(treat_columns)       #lets check the columns that need treatment

13
['Col747', 'Col836', 'Col702', 'Col733', 'Col742', 'Col754', 'Col763', 'Col791', 'Col813', 'Col822', 'Col831', 'Col843', 'Col852']


In [19]:
for col in treat_columns:
    X[col] = X[col].apply(data_treatment)
    XTest[col] = XTest[col].apply(data_treatment)   #lets treat the columns 

In [20]:
X.info()    #lets check the information after data mining

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17521 entries, 0 to 17520
Columns: 2393 entries, Col3 to Col2397
dtypes: float64(846), int64(1547)
memory usage: 319.9 MB


In [21]:
XTest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20442 entries, 0 to 20441
Columns: 2393 entries, Col3 to Col2397
dtypes: float64(848), int64(1545)
memory usage: 373.2 MB


In [22]:
X.isna().sum()

Col3          0
Col4          0
Col5          0
Col6          0
Col7          0
           ... 
Col2393    1174
Col2394    1186
Col2395    1174
Col2396    1174
Col2397    1186
Length: 2393, dtype: int64

In [23]:
X=X.fillna(X.mean())

In [24]:
XTest=XTest.fillna(X.mean())

In [25]:
X.isna().sum()

Col3       0
Col4       0
Col5       0
Col6       0
Col7       0
          ..
Col2393    0
Col2394    0
Col2395    0
Col2396    0
Col2397    0
Length: 2393, dtype: int64

In [26]:
XTest.isna().sum()

Col3       0
Col4       0
Col5       0
Col6       0
Col7       0
          ..
Col2393    0
Col2394    0
Col2395    0
Col2396    0
Col2397    0
Length: 2393, dtype: int64

In [27]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 17521 entries, 0 to 17520
Series name: Col2
Non-Null Count  Dtype
--------------  -----
17521 non-null  int64
dtypes: int64(1)
memory usage: 137.0 KB


In [28]:
y

0        1
1        0
2        0
3        0
4        0
        ..
17516    0
17517    0
17518    0
17519    0
17520    0
Name: Col2, Length: 17521, dtype: int64

In [29]:
y.value_counts()

0    15760
1     1761
Name: Col2, dtype: int64

# lets apply the models  

In [30]:
#applying classification models since the target variable contains only binary numbers 0 and 1

decision tree classifier

In [31]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(X,y)

DecisionTreeClassifier()

In [32]:
y_pred_dt=dt.predict(XTest)

In [33]:
y_pred_dt

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [34]:
train_accuracy_dt=dt.score(X,y)
train_accuracy_dt                     #model has learnt 99 percent which is very good

0.9924661834370184

random forest classifier

In [35]:
from sklearn.ensemble import RandomForestClassifier
Rf=RandomForestClassifier()
Rf.fit(X,y)

RandomForestClassifier()

In [36]:
y_pred_Rf=Rf.predict(XTest)

In [37]:
y_pred_Rf

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [38]:
train_accuracy_Rf=Rf.score(X,y)
train_accuracy_Rf                  #even here the model has learnt 99 percent

0.9924661834370184

k neighbours classifier

In [39]:
from sklearn.neighbors import KNeighborsClassifier
knc=KNeighborsClassifier(n_neighbors=1,metric='minkowski')
knc.fit(X,y)

KNeighborsClassifier(n_neighbors=1)

In [40]:
y_pred_knc=knc.predict(XTest)
y_pred_knc

C:\Users\binod\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [41]:
train_accuracy_knc=knc.score(X,y)
train_accuracy_knc

C:\Users\binod\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9799098224987158

In [42]:
#the train accuracy of the diffirent models are as follows:
print("the accuracy of decision tree classifier is",train_accuracy_dt)
print("the accuracy of random forest classifier is",train_accuracy_Rf)
print("the accuracy of kneighbours classifier is",train_accuracy_knc)


the accuracy of decision tree classifier is 0.9924661834370184
the accuracy of random forest classifier is 0.9924661834370184
the accuracy of kneighbours classifier is 0.9799098224987158


# result

the aim was to predict the values of Col2 for the test dataset 

In [43]:
#the predicted value of Col2 using decision tree is :
y_pred_dt

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [44]:
#all the values cannot be seen so
for i in range(0, len(y_pred_dt)):    
    print(y_pred_dt[i])

0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
1
0
1
1
1
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
1
0
1
1
0
1
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
1
0
1
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
1
0
0
1
0
0
0
1
1
0
0
0
0
1
0
1
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
1
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
1
1
0
0
1
1
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
1


In [45]:
#the predicted values of Col2 using random forest classifier is:
y_pred_Rf

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [46]:
#to see all the values:
for i in range(0, len(y_pred_Rf)):    
    print(y_pred_Rf[i])

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [47]:
#the pedicted values using kneighbours classifier is as follows:
y_pred_knc

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [48]:
for i in range(0, len(y_pred_knc)):    
    print(y_pred_knc[i])

0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
1
0
1
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
